server:
  port: 8081
  servlet:
    context-path: "/api/v1/account"
spring:
  application:
    name: authentication

amazon:
  aws:
    region: ap-southeast-1
    profileName: mobile_group_1_dev
    cognito:
      client-id: 5bblk1i1g2h1t40qbl9s0std9d