server:
  port: 8080
  servlet:
    context-path: /api/v1/trash
spring:
  application:
    name: trash
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: http://localhost:5672
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_Fm8xzxQHY
          jwk-set-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_Fm8xzxQHY/.well-known/jwks.json

amazon:
  aws:
    region: ap-southeast-1
    profileName: mobile_group_1_dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true