spring:
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    host: rabbitmq
amazon:
  aws:
    uri: http://localstack:4566

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka