server:
  port: 8090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://account
          predicates:
            - Path=/api/v1/account/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**
        - id: master
          uri: lb://master
          predicates:
            - Path=/api/v1/master/**
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true