server:
  port: 8090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://account
          predicates:
            - Path=/api/v1/account/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**
        - id: master
          uri: lb://master
          predicates:
            - Path=/api/v1/master/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/api/v1/payment/**
  zipkin:
    base-url: http://localhost:9411
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_Fm8xzxQHY
          jwk-set-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_Fm8xzxQHY/.well-known/jwks.json
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true