server:
  port: 8083
  error:
    include-message: always
  servlet:
    context-path: "/api/v1/file"
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: uploadFile
  zipkin:
    base-url: http://localhost:9411
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_Fm8xzxQHY
          jwk-set-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_Fm8xzxQHY/.well-known/jwks.json

amazon:
  aws:
    region: ap-southeast-1
    profileName: mobile_group_1_dev
    s3-bucket: usege

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true