server:
  port: 8084
  error:
    include-message: always
  servlet:
    context-path: "/api/v1/file"
spring:
  application:
    name: uploadFile
  zipkin:
    base-url: http://localhost:9411
amazon:
  aws:
    region: ap-southeast-1
    profileName: mobile_group_1_dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true